"""'What do I do now?' steps. Kept deterministic so advice is never hallucinated.

The English steps are the source of truth. Hindi and Marathi are fixed strings (TRANSLATIONS below), chosen by
`lang`, never written by an LLM. Names that people must recognise stay as they are in every language: 1930,
cybercrime.gov.in, Sanchar Saathi, Chakshu, UPI, OTP, PIN, CVV, AnyDesk, TeamViewer, SEBI. Every string is listed,
side by side, in docs/translations_review.md (generated by scripts/make_translation_review.py).
"""

GENERIC_STEP = "Don't click links, pay, or reply to this message."
VERIFY_STEP = "Verify through an official channel you find yourself, not one given in the message."

REPORT_STEPS = [
    "If you already paid or shared an OTP: call 1930 (National Cyber Crime Helpline) right now. "
    "The first hour matters most for freezing the money.",
    "File a complaint at cybercrime.gov.in, with screenshots of the message and any payment reference.",
    "Report the sender's number on Sanchar Saathi → Chakshu (sancharsaathi.gov.in), so it can be blocked.",
]

SPECIFIC: dict[str, list[str]] = {
    "digital_arrest": [
        "Hang up. Don't stay on the video call, even if they show uniforms, badges or 'warrants'.",
        "Call your local police station on a number you look up yourself, and tell a family member.",
    ],
    "courier_parcel": [
        "Don't press any IVR option or call back. Check a real shipment only on the courier's official site.",
    ],
    "kyc_block": [
        "Don't open the link. Open your bank's official app or call the number printed on your card.",
    ],
    "electricity": [
        "Don't call the number. Check your bill status on your electricity board's official app or website.",
    ],
    "lottery_prize": ["Ignore it. You can't win something you never entered, and real prizes never ask for a fee."],
    "job_task": [
        "Don't do the 'tasks' or pay any deposit. Small early payouts are bait for a bigger deposit later.",
    ],
    "earnings": ["Ignore unsolicited job offers that promise fixed daily earnings."],
    "investment": [
        "Check the adviser's SEBI registration number on sebi.gov.in before sending anything.",
        "Leave the group. Screenshots of 'profits' in the group are fake.",
    ],
    "otp_request": ["Never share an OTP, UPI PIN, CVV or password, with anyone, for any reason."],
    "remote_access": ["Don't install AnyDesk, TeamViewer or similar. If you already did, uninstall it and call your bank."],
    "job_fee": [
        "Real employers never charge a deposit or fee for a job, a kit or an offer letter. Don't pay; check the company on its official website.",
    ],
    "advance_fee": ["Never pay a fee up front to receive a prize, loan or job. The payment is the scam."],
    "upi_receive": ["Decline the request. Entering your UPI PIN always SENDS money; it never receives it."],
    "upi_impersonation": ["Don't pay. Real fines and fees are paid on official .gov.in portals, never to personal UPI IDs."],
    "family_emergency": [
        "Call the person on their OLD number, or someone who is with them, before sending anything.",
        "Agree on a family code word for emergencies; voice clones can't guess it.",
    ],
    "apk": [
        "Don't install the file. If you did: turn on airplane mode, uninstall the app, and call your bank to block cards/UPI.",
    ],
    "url_apk": [
        "Don't install the file. If you did: turn on airplane mode, uninstall the app, and call your bank to block cards/UPI.",
    ],
    "url_lookalike": ["Don't enter anything on that site. Type the organisation's real address yourself instead."],
}

LOW_RISK_STEPS = [
    "No common scam signs were found, but that is not a guarantee.",
    "If it asks for money, an OTP or a download later on, check again before acting.",
]

# English step -> (Hindi, Marathi). Simple everyday language, not formal or Sanskritised.
TRANSLATIONS: dict[str, tuple[str, str]] = {
    GENERIC_STEP: (
        "इस संदेश में दिए लिंक पर क्लिक न करें, पैसे न भेजें और जवाब न दें।",
        "या संदेशातील लिंकवर क्लिक करू नका, पैसे पाठवू नका आणि उत्तर देऊ नका.",
    ),
    VERIFY_STEP: (
        "संदेश में दिए नंबर या लिंक से नहीं, खुद ढूँढे हुए ऑफिशियल तरीके से जाँच करें।",
        "संदेशात दिलेल्या नंबर किंवा लिंकवरून नाही, तर स्वतः शोधलेल्या अधिकृत मार्गाने खात्री करा.",
    ),
    REPORT_STEPS[0]: (
        "अगर आप पैसे भेज चुके हैं या OTP बता चुके हैं: अभी 1930 (राष्ट्रीय साइबर क्राइम हेल्पलाइन) पर फोन करें। "
        "पैसे रुकवाने के लिए पहला घंटा सबसे ज़रूरी है।",
        "जर तुम्ही पैसे पाठवले असतील किंवा OTP सांगितला असेल: आत्ताच 1930 (राष्ट्रीय सायबर क्राइम हेल्पलाइन) वर फोन करा. "
        "पैसे रोखण्यासाठी पहिला तास सर्वात महत्त्वाचा आहे.",
    ),
    REPORT_STEPS[1]: (
        "cybercrime.gov.in पर शिकायत दर्ज करें। साथ में संदेश के स्क्रीनशॉट और पेमेंट का रेफरेंस नंबर दें।",
        "cybercrime.gov.in वर तक्रार नोंदवा. सोबत संदेशाचे स्क्रीनशॉट आणि पेमेंटचा रेफरन्स नंबर द्या.",
    ),
    REPORT_STEPS[2]: (
        "भेजने वाले का नंबर Sanchar Saathi → Chakshu (sancharsaathi.gov.in) पर रिपोर्ट करें, ताकि उसे बंद कराया जा सके।",
        "पाठवणाऱ्याचा नंबर Sanchar Saathi → Chakshu (sancharsaathi.gov.in) वर रिपोर्ट करा, म्हणजे तो बंद करता येईल.",
    ),
    SPECIFIC["digital_arrest"][0]: (
        "फोन काट दें। वीडियो कॉल पर न रुकें, भले ही वे वर्दी, बैज या 'वारंट' दिखाएँ।",
        "फोन कट करा. व्हिडिओ कॉलवर थांबू नका, त्यांनी गणवेश, बिल्ला किंवा 'वॉरंट' दाखवले तरीही.",
    ),
    SPECIFIC["digital_arrest"][1]: (
        "अपने स्थानीय पुलिस थाने को ऐसे नंबर पर फोन करें जो आपने खुद ढूँढा हो, और घर के किसी सदस्य को बताएँ।",
        "तुमच्या स्थानिक पोलीस ठाण्याला तुम्ही स्वतः शोधलेल्या नंबरवर फोन करा आणि घरातील एखाद्याला सांगा.",
    ),
    SPECIFIC["courier_parcel"][0]: (
        "कॉल में कोई बटन न दबाएँ और वापस फोन न करें। असली शिपमेंट की जाँच सिर्फ़ कूरियर की ऑफिशियल वेबसाइट पर करें।",
        "कॉलमध्ये कोणताही पर्याय (बटण) दाबू नका आणि परत फोन करू नका. खऱ्या पार्सलची माहिती फक्त कुरिअर कंपनीच्या अधिकृत वेबसाइटवर तपासा.",
    ),
    SPECIFIC["kyc_block"][0]: (
        "लिंक न खोलें। अपने बैंक का ऑफिशियल ऐप खोलें या कार्ड पर छपे नंबर पर फोन करें।",
        "लिंक उघडू नका. तुमच्या बँकेचे अधिकृत ॲप उघडा किंवा कार्डवर छापलेल्या नंबरवर फोन करा.",
    ),
    SPECIFIC["electricity"][0]: (
        "उस नंबर पर फोन न करें। अपने बिजली बोर्ड के ऑफिशियल ऐप या वेबसाइट पर बिल की स्थिति देखें।",
        "त्या नंबरवर फोन करू नका. तुमच्या वीज मंडळाच्या अधिकृत ॲप किंवा वेबसाइटवर बिलाची स्थिती तपासा.",
    ),
    SPECIFIC["lottery_prize"][0]: (
        "इसे अनदेखा करें। जिस चीज़ में आपने हिस्सा ही नहीं लिया, उसे आप जीत नहीं सकते, और असली इनाम के लिए कभी फ़ीस नहीं माँगी जाती।",
        "याकडे दुर्लक्ष करा. ज्यात तुम्ही भागच घेतला नाही ते तुम्ही जिंकू शकत नाही, आणि खऱ्या बक्षिसासाठी कधीही फी मागितली जात नाही.",
    ),
    SPECIFIC["job_task"][0]: (
        "'टास्क' न करें और कोई डिपॉज़िट न भरें। शुरू में मिलने वाली छोटी रकम बाद में बड़ा डिपॉज़िट लेने का चारा है।",
        "'टास्क' करू नका आणि कोणतेही डिपॉझिट भरू नका. सुरुवातीला मिळणारी छोटी रक्कम म्हणजे नंतर मोठे डिपॉझिट घेण्यासाठी टाकलेले आमिष आहे.",
    ),
    SPECIFIC["earnings"][0]: (
        "बिना माँगे आए ऐसे नौकरी के ऑफ़र अनदेखे करें जो रोज़ की पक्की कमाई का वादा करते हैं।",
        "न मागता आलेल्या, रोज ठरावीक कमाईचे आश्वासन देणाऱ्या नोकरीच्या ऑफरकडे दुर्लक्ष करा.",
    ),
    SPECIFIC["investment"][0]: (
        "कुछ भी भेजने से पहले sebi.gov.in पर सलाहकार का SEBI रजिस्ट्रेशन नंबर जाँचें।",
        "काहीही पाठवण्यापूर्वी sebi.gov.in वर सल्लागाराचा SEBI नोंदणी क्रमांक तपासा.",
    ),
    SPECIFIC["investment"][1]: (
        "ग्रुप छोड़ दें। ग्रुप में दिखाए गए 'मुनाफ़े' के स्क्रीनशॉट नकली होते हैं।",
        "ग्रुप सोडा. ग्रुपमध्ये दाखवलेले 'नफ्या'चे स्क्रीनशॉट बनावट असतात.",
    ),
    SPECIFIC["otp_request"][0]: (
        "OTP, UPI PIN, CVV या पासवर्ड किसी को भी, किसी भी वजह से, कभी न बताएँ।",
        "OTP, UPI PIN, CVV किंवा पासवर्ड कोणालाही, कोणत्याही कारणासाठी, कधीही सांगू नका.",
    ),
    SPECIFIC["remote_access"][0]: (
        "AnyDesk, TeamViewer या ऐसा कोई ऐप इंस्टॉल न करें। अगर कर चुके हैं, तो उसे हटा दें और अपने बैंक को फोन करें।",
        "AnyDesk, TeamViewer किंवा तसे कोणतेही ॲप इन्स्टॉल करू नका. आधीच केले असेल तर ते काढून टाका आणि तुमच्या बँकेला फोन करा.",
    ),
    SPECIFIC["job_fee"][0]: (
        "असली कंपनी नौकरी, किट या ऑफ़र लेटर के लिए कभी डिपॉज़िट या फ़ीस नहीं लेती। पैसे न दें; कंपनी की ऑफिशियल वेबसाइट पर जाँच करें।",
        "खरी कंपनी नोकरी, किट किंवा ऑफर लेटरसाठी कधीही डिपॉझिट किंवा फी घेत नाही. पैसे देऊ नका; कंपनीच्या अधिकृत वेबसाइटवर खात्री करा.",
    ),
    SPECIFIC["advance_fee"][0]: (
        "इनाम, लोन या नौकरी पाने के लिए पहले से कोई फ़ीस कभी न भरें। वह पैसा माँगना ही धोखा है।",
        "बक्षीस, कर्ज किंवा नोकरी मिळवण्यासाठी आधीच कोणतीही फी भरू नका. ती फी मागणे हाच फसवणुकीचा प्रकार आहे.",
    ),
    SPECIFIC["upi_receive"][0]: (
        "रिक्वेस्ट मना कर दें। UPI PIN डालने से हमेशा पैसे जाते हैं, आते नहीं।",
        "रिक्वेस्ट नाकारा. UPI PIN टाकल्याने नेहमी पैसे जातात, येत नाहीत.",
    ),
    SPECIFIC["upi_impersonation"][0]: (
        "पैसे न भेजें। असली जुर्माना और फ़ीस सरकारी .gov.in पोर्टल पर भरी जाती है, किसी के निजी UPI ID पर नहीं।",
        "पैसे भरू नका. खरा दंड आणि फी सरकारी .gov.in पोर्टलवर भरली जाते, कोणाच्याही वैयक्तिक UPI ID वर नाही.",
    ),
    SPECIFIC["family_emergency"][0]: (
        "कुछ भी भेजने से पहले उस व्यक्ति को उसके पुराने नंबर पर फोन करें, या उसके साथ मौजूद किसी से बात करें।",
        "काहीही पाठवण्यापूर्वी त्या व्यक्तीला तिच्या जुन्या नंबरवर फोन करा, किंवा तिच्यासोबत असलेल्या कोणाशी तरी बोला.",
    ),
    SPECIFIC["family_emergency"][1]: (
        "आपात स्थिति के लिए परिवार में एक सीक्रेट कोड शब्द तय करें; नकली आवाज़ (वॉइस क्लोन) उसे नहीं जान सकती।",
        "आणीबाणीसाठी कुटुंबात एक गुप्त कोड शब्द ठरवा; नकली आवाज (व्हॉइस क्लोन) तो ओळखू शकत नाही.",
    ),
    SPECIFIC["apk"][0]: (
        "वह फ़ाइल इंस्टॉल न करें। अगर कर ली है: फोन को एयरप्लेन मोड में डालें, ऐप हटा दें और कार्ड/UPI बंद कराने के लिए अपने बैंक को फोन करें।",
        "ती फाईल इन्स्टॉल करू नका. केली असेल तर: फोन एअरप्लेन मोडवर टाका, ॲप काढून टाका आणि कार्ड/UPI बंद करण्यासाठी तुमच्या बँकेला फोन करा.",
    ),
    SPECIFIC["url_lookalike"][0]: (
        "उस वेबसाइट पर कुछ भी न भरें। उस संस्था का असली पता खुद टाइप करके खोलें।",
        "त्या वेबसाइटवर काहीही भरू नका. त्या संस्थेचा खरा पत्ता स्वतः टाइप करून उघडा.",
    ),
    LOW_RISK_STEPS[0]: (
        "फ़िलहाल धोखाधड़ी के आम संकेत नहीं मिले, लेकिन यह कोई गारंटी नहीं है।",
        "फसवणुकीची सामान्य चिन्हे आढळली नाहीत, पण ही हमी नाही.",
    ),
    LOW_RISK_STEPS[1]: (
        "अगर आगे चलकर यह पैसे, OTP या कुछ डाउनलोड करने को कहे, तो कुछ करने से पहले फिर जाँच लें।",
        "पुढे जाऊन जर यात पैसे, OTP किंवा काही डाउनलोड करायला सांगितले, तर काही करण्यापूर्वी पुन्हा तपासा.",
    ),
}

_LANG_INDEX = {"hi": 0, "mr": 1}


def translate_step(step: str, lang: str) -> str:
    """The step in `lang`, or the English original for 'en' (or if a string has no translation yet)."""
    pair = TRANSLATIONS.get(step)
    return pair[_LANG_INDEX[lang]] if pair and lang in _LANG_INDEX else step


def all_english_steps() -> set[str]:
    """Every English step this module can ever return (used by the translation tests and the review doc)."""
    steps = {GENERIC_STEP, VERIFY_STEP, *REPORT_STEPS, *LOW_RISK_STEPS}
    for lines in SPECIFIC.values():
        steps.update(lines)
    return steps


def build_actions(verdict: str, signal_ids: list[str], lang: str = "en") -> list[str]:
    if verdict == "low":
        return [translate_step(s, lang) for s in LOW_RISK_STEPS]
    steps: list[str] = [GENERIC_STEP]
    for sid in signal_ids:
        for step in SPECIFIC.get(sid, []):
            if step not in steps:
                steps.append(step)
    if verdict == "scam":
        steps.extend(REPORT_STEPS)
    else:
        steps.append(VERIFY_STEP)
        steps.append(REPORT_STEPS[0])
    return [translate_step(s, lang) for s in steps[:7]]
