"""Write docs/translations_review.md: every Hindi and Marathi string next to its English original.

    python scripts/make_translation_review.py

The sheet is generated from the strings the app really uses (backend/app/actions.py, verdict.py,
rules/translations.py and the I18N block in frontend/index.html), so it can't drift from the code. A test fails if
the committed sheet is out of date. To change a translation, edit it in the code and regenerate this file.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app import actions, verdict  # noqa: E402
from app.rules import translations as sig_tr  # noqa: E402
from app.rules.engine import PATTERNS  # noqa: E402

OUT = ROOT / "docs" / "translations_review.md"

HEADER = """\
# Hindi and Marathi translations: review sheet

Generated by `scripts/make_translation_review.py` from the strings the app really uses. **Don't edit this file by
hand**: send corrections (quote the English line and give the new Hindi/Marathi), they get changed in the code and
this sheet is regenerated.

**Rules followed**
- Simple everyday Hindi and Marathi, not formal or Sanskritised.
- These names are kept exactly as they are, in every language: **1930, cybercrime.gov.in, Sanchar Saathi, Chakshu,
  UPI, OTP, PIN, CVV, KYC, AnyDesk, TeamViewer, SEBI, CBI, APK, QR, WhatsApp, Telegram**.
- `{tld}`, `{brand}`, `{brand_l}`, `{reg}` and `{k}` are filled in by the app (a domain ending, a brand name, a
  website, a country code), so leave them in place.
- The "what to do now" steps and the red-flag text are **fixed strings**, never written by an AI.

**What to check:** meaning is the same as the English; the tone is calm and clear for someone who may be frightened;
nothing sounds like a command to do something unsafe; the wording is what people actually say.
"""


def esc(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def table(rows: list[tuple[str, str, str]]) -> str:
    lines = ["| English | हिंदी (Hindi) | मराठी (Marathi) |", "|---|---|---|"]
    lines += [f"| {esc(e)} | {esc(h)} | {esc(m)} |" for e, h, m in rows]
    return "\n".join(lines)


def step_row(step: str) -> tuple[str, str, str]:
    hi, mr = actions.TRANSLATIONS[step]
    return step, hi, mr


def i18n_blocks() -> dict[str, dict[str, str]]:
    """The I18N object from the page, parsed without running any JavaScript."""
    html = (ROOT / "frontend" / "index.html").read_text("utf-8")
    body = re.search(r"const I18N = \{(.*?)\n\};", html, re.S).group(1)
    blocks: dict[str, dict[str, str]] = {}
    for lang, chunk in re.findall(r"\n  (\w+): \{(.*?)\n  \},", body + "\n", re.S):
        blocks[lang] = {k: json.loads(f'"{v}"') for k, v in re.findall(r'(\w+): "((?:[^"\\]|\\.)*)"', chunk)}
    return blocks


def render_review() -> str:
    out = [HEADER]

    out.append("## 1. Verdict headlines and one-line results\n")
    out.append(table([(e, *verdict.TRANSLATIONS[e]) for e in verdict.TRANSLATIONS]))

    out.append("\n\n## 2. What to do now\n")
    out.append("### Shown with every warning\n")
    out.append(table([step_row(actions.GENERIC_STEP), step_row(actions.VERIFY_STEP)]))
    out.append("\n### When it looks like a scam: report it\n")
    out.append(table([step_row(s) for s in actions.REPORT_STEPS]))
    out.append("\n### When no scam signs were found\n")
    out.append(table([step_row(s) for s in actions.LOW_RISK_STEPS]))
    out.append("\n### Extra steps for a specific kind of scam\n")
    shown: set[str] = set()
    for sid, steps in actions.SPECIFIC.items():
        fresh = [s for s in steps if s not in shown]
        if not fresh:
            out.append(f"#### `{sid}`\n\nSame step as the one above (`apk`).\n")
            continue
        shown.update(fresh)
        out.append(f"#### `{sid}`\n")
        out.append(table([step_row(s) for s in fresh]) + "\n")

    out.append("\n## 3. Red flags (a short title and a one-line reason for each)\n")
    english: dict[str, tuple[str, str]] = {p.id: (p.label, p.why) for p in PATTERNS}
    english.update(sig_tr.ENGLISH_NON_PATTERN)
    for sid, (label, why) in english.items():
        t = sig_tr.SIGNALS[sid]
        out.append(f"#### `{sid}`\n")
        out.append(table([(label, *t["label"]), (why, *t["why"])]) + "\n")

    blocks = i18n_blocks()
    out.append("\n## 4. Page text (buttons, titles, notes)\n")
    out.append("Already live on the site. `<b>` marks bold text and `{a}`, `{b}`, `{n}` are numbers filled in by the page.\n")
    out.append(table([(blocks["en"][k], blocks["hi"].get(k, ""), blocks["mr"].get(k, "")) for k in blocks["en"]]))
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(render_review(), "utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
